// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function send(s, r) {
  r.send(s);
  
}

var Http = {
  send: send
};

var Json = {};

var MySql = {};

exports.Http = Http;
exports.Json = Json;
exports.MySql = MySql;
/* No side effect */
